spring:
  security:
    oauth2:
        resourceserver:
            jwt:
              issuer-uri: "http://127.0.0.1:9000" 
        client:
          registration:
              oauth-client:
                provider: spring
                client-id: oauth-client
                client-secret: 12345678
                authorization-grant-type: authorization_code
                redirect-uri: "http://127.0.0.1:8080/api/v1/security/authorized"
                scope:
                    - openid
                    - profile
                    - read
                    - write
                client-name: oauth-client
          provider:
            spring:
                issuer-uri: "http://127.0.0.1:9000"
          
logging:
  level:
    org.springframework.security: TRACE          